- name : "Cambiar ip forwarding"
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    state: present
    reload: yes
- name : "Cambiar configuración de la red"
  template:
  src: network
  
