- name : "Cambiar ip forwarding"
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    state: present
    reload: yes
- name: "Cambiar configuración de red"
  template:
    src: network/interfaces
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: 0644
  notify:
    - reboot
  
